POST http://localhost:3000/videos

Content-Type: application/json
Accept-Language: en

{
    "title": "Video 01",
    "description": "Este eh o Video 01",
    "duration": 180
}

// utiliza-se o ### para separar a requisições (Request)

###
GET http://localhost:3000/videos
